### ISSUE TITLE
docker-related features enabled

### ISSUE THREAD

**Issue by zhaoyutiandc** [moto-sm8550/android_device_motorola_rtwo-kernel#1]
I appreciate your work and I’m wondering if you could create another branch and compile a kernel with docker-related features enabled. I would like to use docker on my phone and I think it would be useful for other moto x40 users as well. Thank you for your consideration and response

Script used to check the make defconfig.
https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh

**Comment by ThEMarD** [comment]
Heyyo, tbh the kernel isn't exciting right now as we are using a prebuilt kernel, and [the actual kernel repo](https://github.com/moto-sm8550/android_kernel_motorola_sm8550) is only there for the kernel headers we need to compile LineageOS for rtwo... eventually we will get source-built kernel working, but at the same time Motorola needs to release full kernel source code repos

**Comment by zhaoyutiandc** [comment]
@ThEMarD Thank you for your reply. I understand your situation. It’s a pity that the source is not complete
